cc_library(
    name = 'htparse',
    warning = 'no',
    srcs = [
        'htparse.c',
    ]
)

cc_binary(
    name = 'test',
    warning = 'no',
    srcs = [
        'test.c',
    ],
    deps = [
        ':htparse',
    ]
)
